### ISSUE TITLE
看过你的视频和项目好几遍了，这次再细看电路，看出一点强迫症

### ISSUE THREAD

**Issue by Staok** [Dimsmary/OpenSTM#10]
首先，up可能对硬件还少一些实战的经验，这个大多数硬件玩家的遗憾，指出一些问题，纯属当我强迫症罢：
1、芯片的选型很迷，比如DC-DC、Vref参考基准、ADC，还有关键的运放，选的都是死贵死贵的（JLC估计可开心了）又比较老的（有年头的），而且可能不需要高带宽的运放选了，可能Δ-Σ的ADC更好而选择了SAR，TIA电路的跨阻电阻可以选择金属膜的噪声更低（这是TIA电路在业界的普遍认识），选型的门道也很多，一是芯片的调研和使用经验少点，另一个是受到很多国内外的开源项目的选型的影响（很多高性价比的方案都没有开源都是发烧友自己设计的，开源出来的大都很少有货真价实的高性价比的良品），所以这个项目不适合直接供他人打板买芯片然后SMT，成本太太高（富哥除外），适合那些有经验的在你的基础上再优化优化选型和电路等（然后他们选择不开源hhh）。
2、电路的拓扑设计可以更好，比如产生负压的方案，降低噪声纹波的方案，这里面门道需要多看多试验都少不了。然后PCB的走线，尤其是电源部分的噪声控制，我不知道你实际测过纹波没有。然后以上如果深度优化下的话，估计出图效果会更好!

**Comment by Dimsmary** [comment]
抱歉，整个项目都是我个人独立设计的，所以很难顾及所有方面，所以目前所有的设计都是基于「能实现」的目的，而非「最优」的设计。

- 对于您提到的，芯片选型的问题，同样是基于此角度进行选型的。在选型时只是简单考虑了其纸面参数是否能够满足我的目的以及「我」本人是否能够承担其成本。对于外围芯片，如基准电压芯片同样也是基于DAC芯片的数据手册照搬而来。

- 至于您提到的电源纹波以及出图效果，目前我所用的设备精度难以测出ADP5070与ADP7182/7118输出的噪声，所以我暂时肤浅的认为电源部分是足以使用的。目前出图效果较差的原因我认为仍然是系统震动难以消除，这一部分可能可以采用更稳固的压电滑台设计，或提升ADC/DAC速度以解决。

- 但归根结底本项目只是一个爱好者的DIY项目，我无意顾及所有方面，开源也只是为了给想要DIY STM的爱好者提供多一种可选的方案。

但如果您有意优化本项目，也非常欢迎提供进一步的意见，谢谢。
