### ISSUE TITLE
您好，请问如果将音圈电机用于粗进近如何，我觉得可能有可行性

### ISSUE THREAD

**Issue by ZiRuiYu** [Dimsmary/OpenSTM#13]

**Comment by Dimsmary** [comment]
有考虑过，但是音圈电机需要在闭环的情况下才能达到比较高的精度，并且线圈发热可能是个问题？所以当时没有采用。不过我觉得音圈电机能通过某种形式解决这些问题的话，可以把音圈电机用于粗接近。

**Comment by ZiRuiYu** [comment]
好，谢谢
