### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GongJiaBao** [Dimsmary/OpenSTM#3]
可以放出细小零件规格么，例如弹簧

**Comment by Dimsmary** [comment]
目前还在完善技术文档，文档完善后将包括此内容

**Comment by Daivdwang555** [comment]
大佬您好。我们观看了您自制扫描隧道显微镜的视频，想要参照您的电路做一个复刻，但发现AD5761RBRUZ、ADS8685IPWR、ATMEGA328P-MU这三款芯片好像搜不到货源，买不到。想问一下大佬有没有什么解决的方法?

**Comment by Aurora000111** [comment]
好的大佬，留下足迹，我开始复刻了

**Comment by Aurora000111** [comment]
> 

看到这个真的太激动了

**Comment by Aurora000111** [comment]
好的大佬，留下足迹，我开始复刻了，看到这个真的太激动了
希望能将他改进的更有趣

**Comment by ybh618** [comment]
感谢大佬，Star了

**Comment by Anwen758** [comment]
准备开始复现，star先

**Comment by lyqqhgzj** [comment]
B站热门，先star，等完善以后，看看作为一个门外汉能否也复现一下

**Comment by Tain39** [comment]
紧跟大佬的脚步，准备复现一个

**Comment by kurt021** [comment]
太酷了，准备复现一个

**Comment by SiyuanZhangGit** [comment]
留名复现！~！！

**Comment by Dimsmary** [comment]
技术文档已发布，请参阅最新readme，或访问：https://arxiv.org/abs/2310.05413
