### ISSUE TITLE
您好，请教一下薛定谔方程的问题

### ISSUE THREAD

**Issue by testf123** [Dimsmary/OpenSTM#4]
您好，项目不错，我也在做，有个问题想请教一下：
您的文档中，关于薛定谔方程的描述，
![1](https://github.com/Dimsmary/OpenSTM/assets/109737894/8539e94c-d6b8-4ac8-901e-d1d4653c3b6a)

这个与我的理解不一样，我认为应该是这个：
![2](https://github.com/Dimsmary/OpenSTM/assets/109737894/c0a0fa77-1f69-43da-b90f-ff97b3cc5aa9)

尽管不影响最后的结果，因为在V=0的情况下，下文的假设使得前面2个方程都行得通：
![3](https://github.com/Dimsmary/OpenSTM/assets/109737894/e000a159-793b-4d13-9892-246d7ea1865f)

您认为呢？

**Comment by Dimsmary** [comment]
在公式编辑时弄反了，你的公式是正确的，已修正。
